/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fenqile_androidknowledgepoints_jnidemo_JNITools */

#ifndef _Included_com_fenqile_androidknowledgepoints_jnidemo_JNITools
#define _Included_com_fenqile_androidknowledgepoints_jnidemo_JNITools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fenqile_androidknowledgepoints_jnidemo_JNITools
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_fenqile_androidknowledgepoints_jnidemo_JNITools_add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_fenqile_androidknowledgepoints_jnidemo_JNITools
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_fenqile_androidknowledgepoints_jnidemo_JNITools_sub
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_fenqile_androidknowledgepoints_jnidemo_JNITools
 * Method:    mul
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_fenqile_androidknowledgepoints_jnidemo_JNITools_mul
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_fenqile_androidknowledgepoints_jnidemo_JNITools
 * Method:    div
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_fenqile_androidknowledgepoints_jnidemo_JNITools_div
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
