/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fenqile_androidknowledgepoints_jnidemo2_NDKTools */

#ifndef _Included_com_fenqile_androidknowledgepoints_jnidemo2_NDKTools
#define _Included_com_fenqile_androidknowledgepoints_jnidemo2_NDKTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fenqile_androidknowledgepoints_jnidemo2_NDKTools
 * Method:    getStringFromNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fenqile_androidknowledgepoints_jnidemo2_NDKTools_getStringFromNDK
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
